---
- name: Install zsh (Debian)
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == 'Debian'
  tags: [install, zsh]

- name: Install zsh (RedHat)
  ansible.builtin.dnf:
    name: zsh
    state: present
  become: true
  when: ansible_os_family == 'RedHat'
  tags: [install, zsh]

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
  when: ansible_os_family != 'Darwin'
  tags: [config, zsh]

- name: Ensure ~/.zshrc.local exists
  ansible.builtin.copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.zshrc.local"
    force: false
    mode: "0644"
  tags: [config, zsh]
