- name: Bootstrap local environment
  hosts: localhost
  connection: local

  roles:
    - nvim
    - yazi

  tasks:
    - name: Install packages with apt
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - tmux
          - neofetch
        state: present
      when: ansible_distribution == "Ubuntu"
  
    - name: Install packages with brew
      community.general.homebrew:
        name:
          - git
          - tmux
          - fastfetch
        state: present
      when: ansible_distribution == "MacOSX"

