- name: Bootstrap local environment
  hosts: localhost

  tasks:
    - name: Install packages with apt
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - tmux
          - neofetch
        state: present
      when: ansible_distribution == "Ubuntu"
  
  tasks:
    - name: Install packages with brew
      become: yes
      community.general.homebrew:
        name:
          - git
          - tmux
          - fastfetch
        state: present
      when: ansible_distribution == "MacOSX"

