---
- name: Install Neovim and Yazi from source and setup configs
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    dotfiles_dir: "{{ playbook_dir }}/dotfiles"
    config_dir: "{{ ansible_env.HOME }}/.config"
    install_full_applist: false
    dependencies:
      Darwin:
        - cmake
        - ninja
        - gettext
        - rust
      Debian:
        - ninja-build
        - gettext
        - cmake
        - unzip
        - curl
        - build-essential
        - ffmpeg
        - 7zip
        - jq
        - poppler-utils
        - fd-find
        - ripgrep
        - fzf
        - zoxide
        - imagemagick
      RedHat:
        - ninja-build
        - cmake
        - gcc
        - make
        - unzip
        - gettext
        - curl
        - cargo
        - rust

  roles:
    - role: dependencies
    - role: general_apps
    - role: neovim
    - role: yazi
    - role: symlinks
    - role: zsh
