---
- name: Set font destination path for macOS
  ansible.builtin.set_fact:
    font_dest: "~/Library/Fonts"
  when: ansible_os_family == 'Darwin'

- name: Set font destination path for Linux
  ansible.builtin.set_fact:
    font_dest: "~/.local/share/fonts"
  when: ansible_system == 'Linux'

- name: Ensure font directory exists
  ansible.builtin.file:
    path: "{{ font_dest }}"
    state: directory
    mode: "0755"

- name: Copy directories from files to font destination
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ font_dest }}/"
  loop:
    - otf
    - ttf
    - web

- name: Update font cache on Linux
  ansible.builtin.command: fc-cache -fv
  when: ansible_system == 'Linux'
  changed_when: false
