---
- name: Ensure .config directory exists
  file:
    path: "{{ config_dir }}"
    state: directory
  tags: [config]

- name: Find all top-level contents in dotfiles/.config/nvim
  find:
    paths: "{{ dotfiles_dir }}/.config/nvim"
    hidden: yes
    file_type: any
  register: nvim_contents
  tags: [config, nvim]

- name: Ensure ~/.config/nvim exists
  file:
    path: "{{ config_dir }}/nvim"
    state: directory
  tags: [config, nvim]

- name: Symlink nvim contents
  file:
    src: "{{ item.path }}"
    dest: "{{ config_dir }}/nvim/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ nvim_contents.files }}"
  tags: [config, nvim]

- name: Find all top-level contents in dotfiles/.config/yazi
  find:
    paths: "{{ dotfiles_dir }}/.config/yazi"
    hidden: yes
    file_type: any
  register: yazi_contents
  tags: [config, yazi]

- name: Ensure ~/.config/yazi exists
  file:
    path: "{{ config_dir }}/yazi"
    state: directory
  tags: [config, yazi]

- name: Symlink yazi contents
  file:
    src: "{{ item.path }}"
    dest: "{{ config_dir }}/yazi/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ yazi_contents.files }}"
  tags: [config, yazi]