-- Buffer Line (Tab Bar)
--
-- Displays open buffers/tabs as a tab bar at the top of the editor.
-- Configured with slanted separators in tab mode.
--
-- Generated by cursor-agent

return {
  "akinsho/bufferline.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  version = "*",
  opts = {
    options = {
      mode = "tabs",
      separator_style = "slant",
    },
  },
}
