-- CSV Support: Rainbow CSV
--
-- Highlights CSV columns in different colors for easier reading.
-- Uses treesitter-based highlighting.
--
-- Generated by cursor-agent

return {
  "cameron-wags/rainbow_csv.nvim",
  ft = { "csv", "tsv", "csv_semicolon", "csv_whitespace", "csv_pipe", "rfc_csv", "rfc_semicolon" },
  cmd = { "RainbowDelim", "RainbowDelimSimple", "RainbowDelimQuoted", "RainbowMultiDelim" },
  config = true,
}
