-- Undo Tree
--
-- Visualizes the undo history as a tree for non-linear undo navigation.
-- Command: :UndotreeToggle
--
-- Generated by cursor-agent

return {
  "mbbill/undotree",
  config = function()
    vim.g.undotree_WindowLayout = 4
  end,
}
