---
- name: Check if Homebrew is installed (macOS)
  command: command -v brew
  register: brew_check
  ignore_errors: yes
  when: ansible_os_family == 'Darwin'
  tags: [dependencies, install]

- name: Install Homebrew (macOS)
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: ansible_os_family == 'Darwin' and brew_check.rc != 0
  tags: [dependencies, install]

- name: Install macOS dependencies for Neovim and Yazi
  homebrew:
    name: "{{ dependencies['Darwin'] }}"
    state: present
  when: ansible_os_family == 'Darwin'
  tags: [dependencies, install]

- name: Install Debian dependencies for Neovim and Yazi
  apt:
    name: "{{ dependencies['Debian'] }}"
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'
  tags: [dependencies, install]

- name: Check if Rust is installed (Debian)
  stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
  register: cargo_stat
  when: ansible_os_family == 'Debian'
  tags: [dependencies, install]

- name: Install Rust via rustup (Debian)
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  when: ansible_os_family == 'Debian' and not cargo_stat.stat.exists
  tags: [dependencies, install]

- name: Install Fedora/RedHat dependencies for Neovim and Yazi
  dnf:
    name: "{{ dependencies['RedHat'] }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'
  tags: [dependencies, install]

- name: Attempt to install npm
  package:
    name: npm
    state: present
  become: "{{ 'yes' if ansible_os_family != 'Darwin' else 'no' }}"
  ignore_errors: yes
  tags: [dependencies, install]
