---
- name: Install full application list from Brewfile (macOS)
  command: brew bundle --file={{ playbook_dir }}/../Brewfile
  when: ansible_os_family == 'Darwin' and (install_full_applist | default(false) | bool)
  tags: [apps, install, dependencies]

- name: Load linux default apps
  include_vars:
    file: "{{ playbook_dir }}/linux_apps.yml"
  when: ansible_os_family != 'Darwin'
  tags: [apps, install, dependencies]

- name: Install default apps (Debian)
  apt:
    name: "{{ default_apps['Debian'] }}"
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'
  tags: [apps, install, dependencies]

- name: Install default apps (RedHat)
  dnf:
    name: "{{ default_apps['RedHat'] }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'
  tags: [apps, install, dependencies]