---
- name: Install Recommended Apps and Tools
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    dotfiles_dir: "{{ playbook_dir }}/../dotfiles"
    config_dir: "{{ ansible_env.HOME }}/.config"
    install_full_applist: true

  roles:
    - role: dependencies
    - role: general_apps
    - role: lazygit
    - role: hackfont
    - role: yazi
    - role: neovim
    - role: symlinks
    - role: zsh
