-- Status Line: Lualine
--
-- Customizable status line with mode, branch, filename, diff, diagnostics, and filetype.
-- Uses powerline separators and a custom color theme.
--
-- Generated by cursor-agent

return {
  "nvim-lualine/lualine.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    local lualine = require("lualine")
    local lazy_status = require("lazy.status")
    -- to configure lazy pending updates count

    local colors = {
      blue = "#65D1FF",
      green = "#3EFFDC",
      violet = "#FF61EF",
      yellow = "#FFDA7B",
      red = "#FF4A4A",
      orange = "#FF9E64",
      semilightgray = "#8b95a7",
      fg = "#c3ccdc",
      bg = "#112638",
      inactive_bg = "#2c3043",
    }

    local branch_bg = "#45475a"
    local branch_fg = "#cdd6f4"

    local my_lualine_theme = {
      normal = {
        a = { bg = colors.blue, fg = colors.bg, gui = "bold" },
        b = { bg = branch_bg, fg = branch_fg },
        c = { bg = colors.bg, fg = colors.fg },
      },
      insert = {
        a = { bg = colors.green, fg = colors.bg, gui = "bold" },
        b = { bg = branch_bg, fg = branch_fg },
        c = { bg = colors.bg, fg = colors.fg },
      },
      visual = {
        a = { bg = colors.violet, fg = colors.bg, gui = "bold" },
        b = { bg = branch_bg, fg = branch_fg },
        c = { bg = colors.bg, fg = colors.fg },
      },
      command = {
        a = { bg = colors.yellow, fg = colors.bg, gui = "bold" },
        b = { bg = branch_bg, fg = branch_fg },
        c = { bg = colors.bg, fg = colors.fg },
      },
      replace = {
        a = { bg = colors.red, fg = colors.bg, gui = "bold" },
        b = { bg = branch_bg, fg = branch_fg },
        c = { bg = colors.bg, fg = colors.fg },
      },
      terminal = {
        a = { bg = colors.orange, fg = colors.bg, gui = "bold" },
        b = { bg = branch_bg, fg = branch_fg },
        c = { bg = colors.bg, fg = colors.fg },
      },
      inactive = {
        a = { bg = colors.inactive_bg, fg = colors.semilightgray, gui = "bold" },
        b = { bg = colors.inactive_bg, fg = colors.semilightgray },
        c = { bg = colors.inactive_bg, fg = colors.semilightgray },
      },
    }

    -- Shortened mode names
    local mode_map = {
      ["NORMAL"] = "NOR",
      ["INSERT"] = "INS",
      ["VISUAL"] = "VIS",
      ["V-LINE"] = "V-L",
      ["V-BLOCK"] = "V-B",
      ["SELECT"] = "SEL",
      ["S-LINE"] = "S-L",
      ["S-BLOCK"] = "S-B",
      ["REPLACE"] = "REP",
      ["V-REPLACE"] = "V-R",
      ["COMMAND"] = "CMD",
      ["EX"] = "EX",
      ["MORE"] = "MOR",
      ["CONFIRM"] = "CON",
      ["SHELL"] = "SH",
      ["TERMINAL"] = "TER",
    }

    -- configure lualine with modified theme
    lualine.setup({
      options = {
        theme = my_lualine_theme,
        section_separators = { left = "", right = "" },
        component_separators = { left = "", right = "" },
        globalstatus = true,
      },
      sections = {
        lualine_a = {
          {
            "mode",
            fmt = function(str)
              return mode_map[str] or str
            end,
          },
        },
        lualine_b = {
          {
            "filename",
            path = 4, -- 0=filename, 1=relative path, 2=absolute, 3=absolute with ~, 4=filename and parent dir
          },
        },
        lualine_c = {
          { "diff" },
        },
        lualine_x = {
          { "filetype" },
          { "diagnostics" },
        },
        lualine_y = {},
        lualine_z = { "branch" },
      },
      extensions = { "lazy" },
    })
  end,
}
