-- Combined navigation plugins

return {
  -- Miscellaneous Plugins
  --
  -- Simple plugins that don't need their own config files:
  --   - plenary.nvim: Lua utility library (dependency for many plugins)
  --   - vim-tmux-navigator: Seamless navigation between vim and tmux panes
  --
  -- Generated by cursor-agent

  {
    "nvim-lua/plenary.nvim",
    "christoomey/vim-tmux-navigator",
  },

  -- File Explorer: nvim-tree
  --
  -- Sidebar file explorer with git integration.
  -- Keybinding: <leader>ee to toggle, <S-Tab> for file info popup.
  --
  -- Generated by cursor-agent

  {
    "nvim-tree/nvim-tree.lua",
    dependencies = "nvim-tree/nvim-web-devicons",
    config = function()
      local nvimtree = require("nvim-tree")

      -- recommended settings from nvim-tree documentation
      vim.g.loaded_netrw = 1
      vim.g.loaded_netrwPlugin = 1

      nvimtree.setup({
        view = {
          width = 35,
          relativenumber = true,
        },
        -- change folder arrow icons
        renderer = {
          indent_markers = {
            enable = true,
          },
          icons = {
            glyphs = {
              folder = {
                arrow_closed = "", -- arrow when folder is closed
                arrow_open = "", -- arrow when folder is open
              },
            },
          },
        },
        -- disable window_picker for
        -- explorer to work well with
        -- window splits
        actions = {
          open_file = {
            window_picker = {
              enable = false,
            },
          },
        },
        filters = {
          custom = { ".DS_Store" },
        },
        git = {
          ignore = false,
        },
      })

      -- set keymaps
      local keymap = vim.keymap -- for conciseness

      keymap.set("n", "<leader>ee", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file explorer" }) -- toggle file explorer
     -- keymap.set("n", "<leader>ef", "<cmd>NvimTreeFindFileToggle<CR>", { desc = "Toggle file explorer on current file" }) -- toggle file explorer on current file
     -- keymap.set("n", "<leader>ec", "<cmd>nvimtreecollapse<cr>", { desc = "collapse file explorer" }) -- collapse file explorer
     keymap.set("n", "<leader>er", "<cmd>nvimtreerefresh<cr>", { desc = "refresh file explorer" }) -- refresh file explorer
    end
  },

  -- Old Telescope: Fuzzy Finder
  -- Disabling while testing the telescope deployment from github.com/tcmmichaelb139/.dotfiles
  -- {
  --   "nvim-telescope/telescope.nvim",
  --   branch = "0.1.x",
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
  --     "nvim-tree/nvim-web-devicons",
  --     "folke/todo-comments.nvim",
  --   },
  --   config = function()
  --     local telescope = require("telescope")
  --     local actions = require("telescope.actions")
  --
  --     telescope.setup({
  --       defaults = {
  --         path_display = { "smart" },
  --         },
  --       },
  --     })
  --
  --     telescope.load_extension("fzf")
  --   end,
  -- },

  -- New Telescope: Fuzzy Finder
  {
    "nvim-telescope/telescope.nvim",
    cmd = { "Telescope" },
    dependencies = {
      { "nvim-lua/plenary.nvim" },
      { "nvim-telescope/telescope-file-browser.nvim" },
      { "nvim-telescope/telescope-z.nvim" },
      { "nvim-telescope/telescope-symbols.nvim" },
      { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
    },
    config = function()
      require("telescope").setup({
        defaults = {
          vimgrep_arguments = {
            "rg",
            "-L",
            "--color=never",
            "--no-heading",
            "--with-filename",
            "--line-number",
            "--column",
            "--smart-case",
          },
          prompt_prefix = "   ",
          selection_caret = "  ",
          entry_prefix = "  ",
          initial_mode = "insert",
          selection_strategy = "reset",
          sorting_strategy = "ascending",
          layout_strategy = "horizontal",
          layout_config = {
            horizontal = {
              prompt_position = "top",
              preview_width = 0.55,
              results_width = 0.8,
            },
            vertical = {
              mirror = false,
            },
            width = 0.87,
            height = 0.80,
            preview_cutoff = 120,
          },
          file_sorter = require("telescope.sorters").get_fuzzy_file,
          file_ignore_patterns = { "node_modules" },
          generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
          path_display = { "truncate" },
          winblend = 0,
          border = {},
          borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
          color_devicons = true,
          set_env = { ["COLORTERM"] = "truecolor" },
          file_previewer = require("telescope.previewers").vim_buffer_cat.new,
          grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
          qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,
          buffer_previewer_maker = require("telescope.previewers").buffer_previewer_maker,
          mappings = {
            n = {
              ["q"] = require("telescope.actions").close,
            },
          }
        },
      })
      require("telescope").load_extension("file_browser")
    end,
  },




  -- Yazi: Terminal File Manager Integration
  --
  -- Opens the yazi file manager in a floating terminal.
  -- Keybindings: <leader>ey current file, <leader>eY cwd, <leader>iw resume.
  --

  {
    "mikavilpas/yazi.nvim",
    event = "VeryLazy",
    keys = {
      {
        "<leader>ey",
        "<cmd>Yazi<cr>",
        desc = "Open yazi at the current file",
      },
      -- {
      --   "<leader>eY",
      --   "<cmd>Yazi cwd<cr>",
      --   desc = "Open yazi in nvim's working directory",
      -- },
      {
        "<leader>ew",
        "<cmd>Yazi toggle<cr>",
        desc = "Resume the last yazi session",
      },
    },
    opts = {
      -- if you want to open yazi instead of netrw, see below for more info
      open_for_directories = false,
      keymaps = {
        show_help = "<f1>",
      },
    },
  },

}
