-- Combined navigation plugins

return {
  -- Miscellaneous Plugins
  --
  -- Simple plugins that don't need their own config files:
  --   - plenary.nvim: Lua utility library (dependency for many plugins)
  --   - vim-tmux-navigator: Seamless navigation between vim and tmux panes
  --
  -- Generated by cursor-agent
  
  {
    "nvim-lua/plenary.nvim",
    "christoomey/vim-tmux-navigator",
  },

  -- File Explorer: nvim-tree
  --
  -- Sidebar file explorer with git integration.
  -- Keybinding: <leader>ee to toggle, <S-Tab> for file info popup.
  --
  -- Generated by cursor-agent
  
  {
    "nvim-tree/nvim-tree.lua",
    dependencies = "nvim-tree/nvim-web-devicons",
    config = function()
      local nvimtree = require("nvim-tree")
  
      -- recommended settings from nvim-tree documentation
      vim.g.loaded_netrw = 1
      vim.g.loaded_netrwPlugin = 1
  
      nvimtree.setup({
        view = {
          width = 35,
          relativenumber = true,
        },
        -- change folder arrow icons
        renderer = {
          indent_markers = {
            enable = true,
          },
          icons = {
            glyphs = {
              folder = {
                arrow_closed = "", -- arrow when folder is closed
                arrow_open = "", -- arrow when folder is open
              },
            },
          },
        },
        -- disable window_picker for
        -- explorer to work well with
        -- window splits
        actions = {
          open_file = {
            window_picker = {
              enable = false,
            },
          },
        },
        filters = {
          custom = { ".DS_Store" },
        },
        git = {
          ignore = false,
        },
      })
  
      -- set keymaps
      local keymap = vim.keymap -- for conciseness
  
      keymap.set("n", "<leader>ee", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file explorer" }) -- toggle file explorer
     -- keymap.set("n", "<leader>ef", "<cmd>NvimTreeFindFileToggle<CR>", { desc = "Toggle file explorer on current file" }) -- toggle file explorer on current file
     -- keymap.set("n", "<leader>ec", "<cmd>nvimtreecollapse<cr>", { desc = "collapse file explorer" }) -- collapse file explorer
     keymap.set("n", "<leader>er", "<cmd>nvimtreerefresh<cr>", { desc = "refresh file explorer" }) -- refresh file explorer
    end
  },

  -- Telescope: Fuzzy Finder
  --
  -- Fuzzy finder for files, grep, and more. Uses fzf-native for speed.
  -- Keybindings: <leader>ff files, <leader>fs grep, <leader>fr recent, <leader>fc cursor word.
  --
  -- Generated by cursor-agent
  
  {
    "nvim-telescope/telescope.nvim",
    branch = "0.1.x",
    dependencies = {
      "nvim-lua/plenary.nvim",
      { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
      "nvim-tree/nvim-web-devicons",
      "folke/todo-comments.nvim",
    },
    config = function()
      local telescope = require("telescope")
      local actions = require("telescope.actions")
  
      telescope.setup({
        defaults = {
          path_display = { "smart" },
          mappings = {
            i = {
              ["<C-k>"] = actions.move_selection_previous, -- move to prev result
              ["<C-j>"] = actions.move_selection_next, -- move to next result
              ["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
            },
          },
        },
      })
  
      telescope.load_extension("fzf")
  
      -- set keymaps
      local keymap = vim.keymap -- for conciseness
  
      keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Fuzzy find files in cwd" })
      keymap.set("n", "<leader>fr", "<cmd>Telescope oldfiles<cr>", { desc = "Fuzzy find recent files" })
      keymap.set("n", "<leader>fs", "<cmd>Telescope live_grep<cr>", { desc = "Find string in cwd" })
      keymap.set("n", "<leader>fc", "<cmd>Telescope grep_string<cr>", { desc = "Find string under cursor in cwd" })
    end,
  },

  -- Yazi: Terminal File Manager Integration
  --
  -- Opens the yazi file manager in a floating terminal.
  -- Keybindings: <leader>ey current file, <leader>eY cwd, <leader>iw resume.
  --
  -- Generated by cursor-agent
  
  {
    "mikavilpas/yazi.nvim",
    event = "VeryLazy",
    keys = {
      {
        "<leader>ey",
        "<cmd>Yazi<cr>",
        desc = "Open yazi at the current file",
      },
      -- {
      --   "<leader>eY",
      --   "<cmd>Yazi cwd<cr>",
      --   desc = "Open yazi in nvim's working directory",
      -- },
      {
        "<leader>ew",
        "<cmd>Yazi toggle<cr>",
        desc = "Resume the last yazi session",
      },
    },
    opts = {
      -- if you want to open yazi instead of netrw, see below for more info
      open_for_directories = false,
      keymaps = {
        show_help = "<f1>",
      },
    },
  },

}
