-- Miscellaneous Plugins
--
-- Simple plugins that don't need their own config files:
--   - plenary.nvim: Lua utility library (dependency for many plugins)
--   - vim-tmux-navigator: Seamless navigation between vim and tmux panes
--
-- Generated by cursor-agent

return {
  "nvim-lua/plenary.nvim",
  "christoomey/vim-tmux-navigator",
}
