-- Trouble: Diagnostics Panel
--
-- Pretty list for diagnostics, quickfix, todos, and more.
-- Keybindings: <leader>xw workspace, <leader>xd document, <leader>xt todos, <leader>xs split.
--
-- Generated by cursor-agent

return {
  "folke/trouble.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons", "folke/todo-comments.nvim" },
  opts = {
    focus = true,
    modes = {
      diagnostics_split = {
        mode = "diagnostics",
        preview = {
          type = "split",
          relative = "win",
          position = "right",
          size = 0.3,
        },
      },
      todo_right = {
        mode = "todo",
        win = {
          position = "right",
          size = 0.25,
        },
      },
    },
  },
  cmd = "Trouble",
  keys = {
    { "<leader>xw", "<cmd>Trouble diagnostics toggle<CR>", desc = "Open trouble workspace diagnostics" },
    { "<leader>xd", "<cmd>Trouble diagnostics toggle filter.buf=0<CR>", desc = "Open trouble document diagnostics" },
    { "<leader>xq", "<cmd>Trouble quickfix toggle<CR>", desc = "Open trouble quickfix list" },
    { "<leader>xl", "<cmd>Trouble loclist toggle<CR>", desc = "Open trouble location list" },
    { "<leader>xt", "<cmd>Trouble todo_right toggle<CR>", desc = "Open todos in trouble" },
    { "<leader>xs", "<cmd>Trouble diagnostics_split toggle<CR>", desc = "Open trouble with split preview" },
  },
}
