-- Which Key: Keybinding Helper
--
-- Displays available keybindings in a popup after pressing a key prefix.
-- Helps discover and remember keymaps.
--
-- Generated by cursor-agent

return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  init = function()
    vim.o.timeout = true
    vim.o.timeoutlen = 500
  end,
  opts = {
    -- your configuration comes here
    -- or leave it empty to use the default settings
    -- refer to the configuration section below
  },
}
