---
- name: Install Neovim via Homebrew (macOS)
  homebrew:
    name: neovim
    state: present
  when: ansible_os_family == 'Darwin'
  tags: [neovim, install]

- name: Ensure /tmp/neovim directory is removed for a fresh build
  file:
    path: /tmp/neovim
    state: absent
  become: yes
  when: ansible_os_family != 'Darwin'
  tags: [neovim, install]

- name: Ensure /tmp/neovim directory exists
  file:
    path: /tmp/neovim
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: '0755'
  when: ansible_os_family != 'Darwin'
  tags: [neovim, install]

- name: Clone Neovim repository
  git:
    repo: https://github.com/neovim/neovim.git
    dest: /tmp/neovim
    version: stable
    depth: 1
  when: ansible_os_family != 'Darwin'
  tags: [neovim, install]

- name: Build Neovim
  shell: cd /tmp/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"
  when: ansible_os_family != 'Darwin'
  tags: [neovim, install]

- name: Install Neovim
  shell: cd /tmp/neovim && make install
  become: yes
  when: ansible_os_family != 'Darwin'
  tags: [neovim, install]
